# -*- coding: utf-8 -*-
"""ASSIGNMENT-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aY9_iN7RBfw49lpclySbPQeWSzk0trRM
"""

import numpy as np
import pandas as pd
import os
import sys
import matplotlib.pyplot as plt
from osgeo import gdal

from google.colab import drive
drive.mount('/content/drive')

file = gdal.Open("/content/drive/MyDrive/SDSA_DATA/aviris_hyperspectral_data/19920612_AVIRIS_IndianPine_NS-line.tif")

data = file.GetRasterBand(1).ReadAsArray()[:,:]
data.shape

data_list = []
for i in range(1,221):
  data_list.append(file.GetRasterBand(i).ReadAsArray()[:,:])

x = 0
for i in data_list:
  if x == 0:
    df= pd.DataFrame(data = i.reshape(-1,614*2678))
    x += 1
  else:
    df= pd.concat([df, pd.DataFrame(data = i.reshape(-1,614*2678))])

df

df = df.transpose()
df

df.columns = [f'Band {i} ' for i in range(1,221)]
df

"""PCA for dimensionality reduction"""

from sklearn.decomposition import PCA

pca = PCA(n_components = 20)
pca_data = pca.fit_transform(df.iloc[:, :-1].values)

df_pca = pd.DataFrame(pca_data)

df_pca

"""fig = plt.figure(figsize = (20, 10))

for i in range(1, 21):
    fig.add_subplot(10,10, i)
    plt.imshow(df_pca.loc[:, f'PC-{i}'].values.reshape(614, 2678), cmap='nipy_spectral')
    plt.axis('off')
    plt.title(f'band - {i}')"""

df_pca.to_csv('NS-line_PCA.csv', index=False)

"""Using LULC (Unsupervised - KMeans)"""

# Labels defined, not used
labels = [' urban land', 'barren land', 'vegetation', 'water body', 'open area']

labels = pd.DataFrame(labels)
labels

from sklearn.cluster import KMeans
kmeans_model= KMeans(n_clusters = 5, max_iter = 1000).fit(df_pca)

"""KMmodel = KMeans(n_clusters=5) 
KMmodel.fit(df_pca)
KM_train = list(KMmodel.predict(df_pca))"""

kmeans_centroids = kmeans_model.cluster_centers_

kmeans_centroids.shape

image_data = pd.read_csv('NS-line_PCA.csv')

# To visualize but session crashed

"""
import seaborn as sns; sns.set(style="ticks", color_codes=True)
band_names = [f'Band {i}' for i in range(0,221)]
seaborn_params = {'alpha': 0.15, 's': 20, 'edgecolor': 'k'}

plot=sns.pairplot(df_pca1, vars=band_names, hue='group', plot_kws = seaborn_params)
plot._legend.remove()
"""

pred_clusters= kmeans_model.predict(image_data)
pred_clusters = pd.DataFrame({'Predictions':pred_clusters})

pred_clusters.head(50)

pred_clusters.to_csv('Predictions.csv', index=False)

# Saving Predictions

predictions = pd.read_csv('Predictions.csv')
predictions.head()

# Plot
plot = kmeans_model.fit_predict(df_pca).reshape((614, 2678))

plot

plt.figure(figsize = (100,100))
plt.imshow(plot)
plt.show()

plt.figure(figsize = (30,30))
plt.imshow(plot, cmap = 'nipy_spectral')

